@startuml
'States
start
if (příznak timeout_t1?) then (ano)
    :nastav příznak ukončení spojení;
else (ne)
if (aktuální stav = Zastavene?) then (ano)
:Tělo stavu Zastavene;
else (ne)
endif
if (aktuální stav = Spustene?) then (ano)
:Tělo stavu Spustene;
else (ne)
endif
if (aktuální stav = čekající?) then (ano)
:Tělo stavu čekající;
else (ne)
endif
endif
if (příznak ukočené spojení?) then (ano)
    :Ukončit všechny asynchronní úlohy;
    :smazat instanci spojení;
    end
else (ne)
endif
stop
@enduml

@startuml
'State 1
start
if (stav spojeni = Zastavene?) then (ano)
 if (apdu = U-formát?) then (ano)
      if (apdu = TESTFR act?) then (ano)
        :vytvoř odpoveď TESTFR con;
        :odešli odpověď\nsession.send();
      else (ne)
      endif
  else (ne)
endif
else (ne)
endif
stop
@enduml

@startuml
'State 2
skinparam DefaultFontSize 16
start
if (stav spojeni = Spustene?) then (ano)
 if (apdu = I-formát?) then (ano)
      if (SSN - VR > 1?) then (ano)
        :Nastala chyba\n   sekvence;
        :pošli poslední stav VR;
        :odešli S-formát\nsession.send();
        :ukonči spojení;
      else (ne)
        :VR++;
        :odstraň všechny \npotvrzené rámce \ns hodnotou <= RSN;
        :odešli data z rámce\n do MQTT brokeru;
        if (počet přijatých rámců ve \n vyrovnávací paměti >= w?) then (ano)
            :odešli S-formát\nsession.send();
        else (ne)
        endif
      endif
  else (ne)

endif
if (apdu = S-formát?) then (ano)
            :odstraň všechny \npotvrzené rámce \ns hodnotou <= RSN;
      else (ne)

      endif
      if (apdu = U-formát?) then (ano)
              if (apdu = TESTFR act?) then (ano)
                :vytvoř odpoveď\n TESTFR con;
                :odešli odpověď\nsession.send();
              else (ne)
              endif
          else (ne)
          endif
else (ne)
endif
stop
@enduml

@startuml
'State 3
start
if (stav spojeni = čekající?) then (ano)
 if (apdu = S-formát?) then (ano)
            :odstraň všechny \npotvrzené rámce \ns hodnotou <= RSN;
      else (ne)
      endif
      if (apdu = U-formát?) then (ano)
              if (apdu = TESTFR act?) then (ano)
                :vytvoř odpoveď\n TESTFR con;
                :odešli odpověď\nsession.send();
              else (ne)
              endif
          else (ne)
          endif
else (ne)
endif
stop
@enduml

