@startuml ServerIEC104
set namespaceSeparator none
class "ServerIEC104" as main.ServerIEC104 {
  async_time : float
  clients : dict[str, ClientManager]
  config_loader : ConfigLoader | None
  ip : str
  k
  name
  no_overflow : int
  port : int
  session_params : tuple
  task_check_alive_queue : Optional[asyncio.Task | None]
  tasks : list
  timeout_t0
  timeout_t1
  timeout_t2
  timeout_t3
  w
  check_alive_clients() -> bool
  close() -> None
  handle_client(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None
  listen() -> None
  load_params(config_loader: ConfigLoader) -> tuple
  periodic_event_check()
  run() -> None
  {abstract}send() -> None
}
@enduml
