@startuml
autonumber
skinparam DefaultTextSize 15

participant ServerIEC104 as server
participant ClientManager as clientmanager
participant Session as session


activate server #FFBBBB

server -> clientmanager: Příchozí spojení od klienta,\n vytvoření instance ClientManager
note left : Server naslouchá\n na TCP 2404 a v\n nekonečné smyčce\nčeká na nové spojení
activate clientmanager #DADBBB

clientmanager -> session: Vytvoření instance spojení
deactivate clientmanager
activate session #8
note right : handle_messages()\ns metodou read(),\nmetoda běží \nv nekonečné smyčce


session -> clientmanager: callback - přijat rámec STARTDT ACT
note right : Klient zahájil přenos
activate clientmanager #00AAAA
note left : Zpracování rámce, aktualizace stavu spojení na "připojeno",\ngenerace odpovědi

clientmanager -> session: Odpověď STARTDT CON
deactivate clientmanager

activate session #Lime
note right: Odeslání metodou send()
return odesláno



session -> clientmanager: callback přijat rámec s daty I(0,0)
note right : přišel povel\npro vyčtení teploty
activate clientmanager
note left : Zpracování rámce, data uložena do databáze\n a předána do modulu zpracování\n

clientmanager -> session: Odpověd I(0,1), data: měřená hodnota
note left : vygenerovaná odpověď s hodnotou měřené teploty\n vrácena od modulu zpracování
deactivate clientmanager
activate session #Lime
return odesláno


session -> clientmanager: callback přijat rámec s daty I(1,1)
note right : zde přišel povel\npro sepnutí LED diody
activate clientmanager
note left : Opět předáno modulu zpracování a uloženo do databáze

clientmanager -> session: Odpověd I(1,2), data: potvrzení

note left : vygenerovaná odpověď s potvrzením sepnutí LED\n vrácena od modulu zpracování
deactivate clientmanager
activate session #Lime
return odesláno


session -> clientmanager: callback přijat rámec STOPDT ACT
note right : Klient ukončil přenos a \nukončil spojení
activate clientmanager #00AAAA
note left : Zpracování rámce, aktualizace stavu spojení na "zastaveno",\ngenerace odpovědi

clientmanager -> session: Odpověď STOPDT CON
deactivate clientmanager

activate session #Lime
note right: Odeslání metodou send()
return smazání instance spojení




deactivate session
destroy session
clientmanager -[dotted]> server: smazání instance ClientManager
note left : čeká na nové spojení
destroy clientmanager



'activate server #FFCBBB


deactivate clientmanager
@enduml