@startuml
autonumber
participant ServerIEC104 as server
participant ClientManager as clientmanager
participant Session as session


activate server #FFBBBB

server -> clientmanager: Příchozí spojení od klienta,\n vytvoření instance ClientManager
note left : Server naslouchá na TCP portu 2404 \n Po příchozím spojení naslouchá dál
activate clientmanager #DADBBB

clientmanager -> session: Vytvoření instance spojení
deactivate clientmanager
activate session #E
note right : Spuštění metody read() \nmetoda běží v nekonečné smyčce

session -> clientmanager: callback přijat rámec STARTDT ACT
activate clientmanager
note right : Aktualizace časovačů
note left : Zpracování rámce, aktualizace stavu spojení na připojeno,\n generace odpovědi


clientmanager -> session: Odpověď STARTDT CON
deactivate clientmanager
activate session #Lime

note right: Odeslání metodou send()
return odesláno

session -> clientmanager: callback přijat rámec s daty I(0,0)
activate clientmanager
note left : Zpracování rámce, užitečná data uložena do databáze,\n
deactivate clientmanager


session -> clientmanager: callback přijat rámec s daty I(1,0)
activate clientmanager
deactivate clientmanager
session -> clientmanager: callback přijat rámec s daty I(2,0)
activate clientmanager
deactivate clientmanager


clientmanager -> session: Vypršel timeout t2, zaslání potvrzení S(2)
note right: Odeslání metodou send()
note left : \n neposílají se žádná data \n
activate session #Lime
return odesláno

clientmanager -> session: Vypršel timeout t1, ukončení spojení
note left : \n neposílají se žádná data \n
deactivate session
return smazání instance spojení
destroy session
clientmanager -[dotted]> server: smazání instance ClientManager
note left : čeká na nové spojení
destroy clientmanager



'activate server #FFCBBB


deactivate clientmanager
@enduml