@startuml
skinparam DefaultFontSize 18

|#whitesmoke|Session|
|#lightgray|ClientManager|
|Modul zpracování|
start
note: start
:vygenerovaná odpověď\n          po bytech;

|#lightgray|ClientManager|
:callback odeslat odpověď;
if (stav spojení spuštěno?) is (ano) then
    :   vytvoření nového rámce s daty\nnew_apdu = generate-I-format(data);
    |#whitesmoke|Session|
    :odeslat rámec;
    stop
    note right: zde není spojení\n ukončeno
else
endif
|#lightgray|ClientManager|
stop
note right: zde není spojení\n ukončeno
@enduml
