@startuml packages
set namespaceSeparator none
package "ClientManager" as ClientManager {
}
package "Frame" as Frame {
}
package "IDataSharing" as IDataSharing {
}
package "IFormat" as IFormat {
}
package "MQTTProtocol" as MQTTProtocol {
}
package "Packet_buffer" as Packet_buffer {
}
package "Parser" as Parser {
}
package "SFormat" as SFormat {
}
package "Session" as Session {
}
package "State" as State {
}
package "Timer" as Timer {
}
package "UFormat" as UFormat {
}
package "acpi" as acpi {
}
package "aio_mqttt" as aio_mqttt {
}
package "client_async" as client_async {
}
package "config_loader" as config_loader {
}
package "mqtt" as mqtt {
}
package "server_async" as server_async {
}
ClientManager --> Frame
ClientManager --> IFormat
ClientManager --> MQTTProtocol
ClientManager --> Packet_buffer
ClientManager --> SFormat
ClientManager --> Session
ClientManager --> UFormat
ClientManager --> acpi
Frame --> acpi
IFormat --> Frame
MQTTProtocol --> IDataSharing
Packet_buffer --> Frame
Parser --> IFormat
Parser --> SFormat
Parser --> UFormat
Parser --> acpi
SFormat --> Frame
Session --> Frame
Session --> IFormat
Session --> Packet_buffer
Session --> Parser
Session --> State
Session --> Timer
UFormat --> Frame
UFormat --> acpi
client_async --> ClientManager
client_async --> Session
client_async --> config_loader
server_async --> ClientManager
server_async --> Session
server_async --> config_loader
@enduml
