@startuml
top to bottom direction
'left to right direction
'skinparam lineType ortho
'skinparam linetype polyline
'scale 600 width
skinparam DefaultFontSize 25

state "ZASTAVENÉ\nspojení" as zastavene
zastavene :
state "SPUŠTĚNÉ\nspojení" as spustene
spustene:
state "Čekající\nNEPOTVRZENÉ\nZASTAVENÉ\nspojení" as cekajici
cekajici :
state "Start" as start
note left of start : Spojení navázáno
state "Stop" as stop
note left of stop : Spojení skončeno

start --> zastavene
zastavene -> zastavene: U-rámec[]/
zastavene --> stop: Časová prodleva t1[]/\nAktivní ukončení\nnebo S-rámec[]/Aktivní ukončení\nnebo I-rámec[]/Aktivní ukončení
zastavene --> spustene: STARTDT act[]\n/Vyslán STARTDT con

spustene --> spustene: U-rámec[]/\nnebo S-rámec[]/\nnebo I-rámec[]/
spustene --> stop: Časová prodleva t1[]/\nAktivní ukončení
spustene -> cekajici: STOPDT act[nepotvrzené I-rámce]
spustene -> zastavene: STOPDT act\n[bez nepotvrzených I-rámců]\n/Vyslán STOPDT con

cekajici --> stop: Časová prodleva t1[]/\nAktivní ukončení\nnebo I-rámec[]/Aktivní ukončení

cekajici --> cekajici: U-rámec[]/\nnebo S-rámec[]/
cekajici ----> zastavene: S-rámec\n[bez nepotvrzených\nI-rámců]\n/Vyslán\nSTOPDT con

@enduml